apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chart-staging
  namespace: argocd
spec:
  project: staging
  source:
    repoURL: 'https://iamdo.github.io/argo-test-chart-repo/'
    targetRevision: 0.2.50
    chart: argo-test-chart
    helm:
      parameters:
        - name: application
          value: chart-staging
        - name: greeting
          value: Hello from Staging!
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chart-staging
  syncPolicy: {}
