apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: resource
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: resource-test-dep
      eventSourceName: resource
      eventName: example
  triggers:
    - template:
        name: argo-workflow
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: resource-workflow-
                labels:
                  app: resource-workflow
              spec:
                entrypoint: whalesay
                arguments:
                  parameters:
                  - name: message
                    # the value will get overridden by the event payload from resource-test-dep
                    value: hello world
                templates:
                - name: whalesay
                  inputs:
                    parameters:
                    - name: message
                  container:
                    image: docker/whalesay:latest
                    command: [cowsay]
                    args: ["{{inputs.parameters.message}}"]
          parameters:
            - src:
                dependencyName: resource-test-dep
                dataKey: body
              dest: spec.arguments.parameters.0.value
      retryStrategy:
        steps: 3
