apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: resource
spec:
  template:
    serviceAccountName: operate-workflow-sa
    container:
      env:
        - name: DEBUG_LOG
          value: "true"
  dependencies:
    - name: resource-test-dep
      eventSourceName: resource
      eventName: example
  triggers:
    - template:
        name: log-trigger
        log:
          intervalSeconds: 360
