apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chart-production
  namespace: argocd
spec:
  project: production
  source:
    repoURL: 'https://iamdo.github.io/argo-test-chart-repo/'
    targetRevision: 0.1.1
    chart: argo-test-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: chart-production
  syncPolicy: {}
