apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bamboo-workflow
spec:
  entrypoint: hello-world
  arguments:
    parameters:
    - name: commit_id
      value: ""
    - name: container_repo_url
      value: ""
    - name: container_tag
      value: ""
    - name: git_repo_url
      value: ""
  templates:
  - name: hello-world
    dag:
      tasks:
      - name: say-hello
        template: say-something
  - name: say-something
    container:
      image: alpine:latest
      command: ["echo"]
      args: ["commit_id: {{workflow.parameters.commit_id}}\ncontainer_repo_url: {{workflow.parameters.container_repo_url}}\ncontainer_tag: {{workflow.parameters.container_tag}}\ngit_repo_url: {{workflow.parameters.git_repo_url}}"]
