apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bamboo-workflow
spec:
  entrypoint: hello-world
  arguments:
    parameters:
    - name: message
      value: "Hello, world!"
  templates:
  - name: hello-world
    dag:
      tasks:
      - name: say-hello
        template: say-something
  - name: say-something
    container:
      image: alpine:latest
      command: ["echo"]
      args: ["{{workflow.parameters.message}}"]
