apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: bamboo-webhook-sensor
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: bamboo-dep
      eventSourceName: bamboo-webhook-eventsource
      eventName: bamboo-event
  triggers:
    - template:
        name: workflow-trigger
        argoWorkflow:
          group: argoproj.io
          version: v1alpha1
          kind: Workflow
          operation: submit
          metadata:
            generatename: bamboo-triggered-workflow
          spec: helm-chart-steps
          workflowTemplateRef:
            name: deploy-chart
            clusterScope: false
