apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: git-
spec:
  entrypoint: clone-repo
  templates:
    - name: clone-repo
      container:
        image: alpine/git
        command: ["git"]
        args: ["clone", "https://github.com/iamDo/argo-test-charts.git"]
      outputs:
        artifacts:
          - name: output-artifact
            path: "/git/argo-test-charts"
    - name: make-helm-package
      container:
        image: alpine
        command: ['ls']
      inputs:
        artifacts:
          - name: output-artifact
            path: '/'
