apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: some-template
spec:
  entrypoint: helm-chart-steps
  templates:
    - name: helm-chart-steps
      steps:
        - - name: clone-repo
            template: clone-repo
        - - name: make-helm-package
            template: make-helm-package
            arguments:
              parameters:
                - name: version-number
                  value: "{{steps.clone-repo.outputs.parameters.version-number}}"
              artifacts:
                - name: git-artifact-input
                  from: "{{steps.clone-repo.outputs.artifacts.git-artifact}}"
        - - name: update-repo-index
            template: update-repo-index
            arguments:
              parameters:
                - name: version-number
                  value: "{{steps.clone-repo.outputs.parameters.version-number}}"
              artifacts:
                - name: helm-chart
                  from: "{{steps.make-helm-package.outputs.artifacts.helm-chart}}"
        - - name: promote-to-staging
            template: manual-confirmation
        - - name: deploy-to-staging
            template: deploy-to-environment
            arguments:
              parameters:
                - name: version-number
                  value: "{{steps.clone-repo.outputs.parameters.version-number}}"
                - name: environment
                  value: staging
        - - name: promote-to-production
            template: manual-confirmation
        - - name: deploy-to-production
            template: deploy-to-environment
            arguments:
              parameters:
                - name: version-number
                  value: "{{steps.clone-repo.outputs.parameters.version-number}}"
                - name: environment
                  value: production
    - name: clone-repo
      container:
        image: ghcr.io/iamdo/clone-repo-get-revs:0.1.2
        command: ["/scripts/entrypoint.sh"]
      outputs:
        parameters:
          - name: version-number
            valueFrom:
              path: '/git/rev-count'
        artifacts:
          - name: git-artifact
            path: '/git/argo-test-charts'
    - name: make-helm-package
      container:
        image: alpine/helm
        command: ['helm']
        args: ['package', '/git']
      outputs:
        artifacts:
          - name: helm-chart
            path: '/apps/argo-test-chart-0.2.{{inputs.parameters.version-number}}.tgz'
      inputs:
        parameters:
          - name: version-number
        artifacts:
          - name: git-artifact-input
            path: '/git'
    - name: update-repo-index
      container:
        image: ghcr.io/iamdo/create-new-repo-index:0.1.7
        command: ["/scripts/entrypoint.sh"]
      inputs:
        parameters:
          - name: version-number
        artifacts:
          - name: helm-chart
            path: '/chart/argo-test-chart-0.2.{{inputs.parameters.version-number}}.tgz'
    - name: manual-confirmation
      suspend: {}
    - name: deploy-to-environment
      container:
        image: ghcr.io/iamdo/deploy-to-environment:0.1.3
        command: ["/scripts/entrypoint.sh"]
        args: ["{{inputs.parameters.environment}}", "{{inputs.parameters.version-number}}"]
      inputs:
        parameters:
          - name: environment
          - name: version-number
