apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-
spec:
  entrypoint: alpine-hello
  templates:
    - name: alpine-hello
      container:
        image: ghcr.io/iamdo/test-image
        command: [echo]
        args: ["hello world"]
