apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: hello-workflow-template
spec:
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: alpine-hello-template
      inputs:
        parameters:
          - name: message
      container:
        image: ghcr.io/iamdo/test-image:0.1.0
        command: [echo]
        args: ["{{inputs.parameters.message}}"]
